### ISSUE TITLE
Add fields

### ISSUE THREAD

**Issue by lauralindal** [codingcats/fczb-adressdatenbank#16]
We still need to add fields such as "Title" and "Zusatz" and such, according to the excel file example. I just can't find it.

**Comment by lauralindal** [comment]
Found it!

To contacts, add:
Title, Form of Address, Position, Phone number, Mobile number, Fax number, Web address (?)

To institutions, add:
Zusatz

**Comment by noobiba** [comment]
Form of address..? Postal or mail? Do we need that? Or intended a form to fill in? Position should be free to fill in or should be a list of options to select from? I guess there are not so many different Anreden.

**Comment by lauralindal** [comment]
Postal/Digital would be an attribute of occasions.
I wanted to make a difference between (Frau/Mann/Dr.) and (Sehr geehrte/Liebe/Hallo), but maybe this doesnt make any sense? Let's diskuss tomorrow.

**Comment by lauralindal** [comment]
tbd: make dispatch_type from boolean into enum

**Comment by tankgrrl** [comment]
Resolved in 397842e9088b1b642e7a830f670b53795974d091
