### ISSUE TITLE
Sort by categories

### ISSUE THREAD

**Issue by lauralindal** [codingcats/fczb-adressdatenbank#25]
Als Nutzer muss ich die Daten meiner Kunden nach bestimmten Kriterien (PLZ, Name, Institution, Anlass, etc.) sortieren können, um die relevanten Kontakte für Mailings zu erhalten.

Als Nutzer muss ich die Daten meiner Kunden nach verschiedenen Kategorien nacheinander sortieren können, um die relevanten Kontakte für Mailings zu erhalten.

(User Story Number 8&9)

**Comment by schultyy** [comment]
Sorting via GET parameter:
```
?field=plz&direction=ASC
```
`field` sagt, nach welchem Feld sortiert werden soll, `direction` sagt, ob aufsteigend oder absteigend

**Comment by tankgrrl** [comment]
Use this Railscast-link: http://railscasts.com/episodes/228-sortable-table-columns
(also for adding arrows in css)
